services:
  python:
    container_name: ${COMPOSE_PROJECT_NAME}_python
    platform: linux/amd64
    build:
      context: ./python
      secrets:
          - CONTAINER_USER_PASSWORD
      dockerfile: Dockerfile
      args:
        - PYTHON_IMAGE=${PYTHON_IMAGE}
        - CONTAINER_USER_NAME=${CONTAINER_USER_NAME}
        - CONTAINER_USER_ID=${HOST_USER_ID}
        - CONTAINER_SOURCE_ROOT=${CONTAINER_SOURCE_ROOT}
        - PYTHON_PORT=${PYTHON_PORT}
    tty: true
    ports:
      - ${PYTHON_PORT}:8000
    volumes:
      - ${PROJECT_PATH}:${CONTAINER_SOURCE_ROOT}
      - ${HOST_SSH_DIR}:${CONTAINER_SSH_DIR}

secrets:
    CONTAINER_USER_PASSWORD:
        environment: CONTAINER_USER_PASSWORD